//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Input/InputManager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputManager : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputManager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputManager"",
    ""maps"": [
        {
            ""name"": ""Flying"",
            ""id"": ""d34a87c2-87b7-49eb-9001-c144adcd0cb1"",
            ""actions"": [
                {
                    ""name"": ""RFly"",
                    ""type"": ""Value"",
                    ""id"": ""a86db424-4e9a-44ab-88d6-3b376bd67cb7"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Grip"",
                    ""type"": ""Button"",
                    ""id"": ""b2cee6c3-6467-412a-8e7e-baa10330f6d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LFly"",
                    ""type"": ""Value"",
                    ""id"": ""62bd8231-fa26-4de2-ac16-68ecf62e3b48"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""1f1c0f2a-e57c-4f16-9200-2deb9a7f9284"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b4e2b5a6-fd8f-4c42-a753-6f3e4c831925"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e9434b9-e2eb-449f-a464-a5ae24936846"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dab2dc38-2012-453d-a3ed-9527a3e0affc"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9e36eeb-f3b2-4630-ab76-f9fae5497f8b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""1dc71342-8c52-4281-9f91-5b559d2b3437"",
            ""actions"": [
                {
                    ""name"": ""ToggleCars"",
                    ""type"": ""Button"",
                    ""id"": ""2c51386d-f675-4856-9669-dfd47ac864f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleText"",
                    ""type"": ""Button"",
                    ""id"": ""5e3aafc6-b2d8-4964-921a-17c79fa71e1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncreaseVelocity"",
                    ""type"": ""Button"",
                    ""id"": ""db2402e3-b35e-438d-b6b9-1aa716420eab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DecreaseVelocity"",
                    ""type"": ""Button"",
                    ""id"": ""0ce78f2d-e07b-42fa-84bf-728ef2d3e013"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""81def1e4-c0f8-46db-8cf0-c2cff08788ed"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleCars"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dfef8dd-6c8c-4b15-9b62-2dbba323cd52"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleText"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06b681dc-6411-4a83-b16f-c3a16f1c200a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""109bea9f-7114-400a-820d-8479bb475334"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Flying
        m_Flying = asset.FindActionMap("Flying", throwIfNotFound: true);
        m_Flying_RFly = m_Flying.FindAction("RFly", throwIfNotFound: true);
        m_Flying_Grip = m_Flying.FindAction("Grip", throwIfNotFound: true);
        m_Flying_LFly = m_Flying.FindAction("LFly", throwIfNotFound: true);
        m_Flying_Pause = m_Flying.FindAction("Pause", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_ToggleCars = m_Debug.FindAction("ToggleCars", throwIfNotFound: true);
        m_Debug_ToggleText = m_Debug.FindAction("ToggleText", throwIfNotFound: true);
        m_Debug_IncreaseVelocity = m_Debug.FindAction("IncreaseVelocity", throwIfNotFound: true);
        m_Debug_DecreaseVelocity = m_Debug.FindAction("DecreaseVelocity", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Flying
    private readonly InputActionMap m_Flying;
    private IFlyingActions m_FlyingActionsCallbackInterface;
    private readonly InputAction m_Flying_RFly;
    private readonly InputAction m_Flying_Grip;
    private readonly InputAction m_Flying_LFly;
    private readonly InputAction m_Flying_Pause;
    public struct FlyingActions
    {
        private @InputManager m_Wrapper;
        public FlyingActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @RFly => m_Wrapper.m_Flying_RFly;
        public InputAction @Grip => m_Wrapper.m_Flying_Grip;
        public InputAction @LFly => m_Wrapper.m_Flying_LFly;
        public InputAction @Pause => m_Wrapper.m_Flying_Pause;
        public InputActionMap Get() { return m_Wrapper.m_Flying; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlyingActions set) { return set.Get(); }
        public void SetCallbacks(IFlyingActions instance)
        {
            if (m_Wrapper.m_FlyingActionsCallbackInterface != null)
            {
                @RFly.started -= m_Wrapper.m_FlyingActionsCallbackInterface.OnRFly;
                @RFly.performed -= m_Wrapper.m_FlyingActionsCallbackInterface.OnRFly;
                @RFly.canceled -= m_Wrapper.m_FlyingActionsCallbackInterface.OnRFly;
                @Grip.started -= m_Wrapper.m_FlyingActionsCallbackInterface.OnGrip;
                @Grip.performed -= m_Wrapper.m_FlyingActionsCallbackInterface.OnGrip;
                @Grip.canceled -= m_Wrapper.m_FlyingActionsCallbackInterface.OnGrip;
                @LFly.started -= m_Wrapper.m_FlyingActionsCallbackInterface.OnLFly;
                @LFly.performed -= m_Wrapper.m_FlyingActionsCallbackInterface.OnLFly;
                @LFly.canceled -= m_Wrapper.m_FlyingActionsCallbackInterface.OnLFly;
                @Pause.started -= m_Wrapper.m_FlyingActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_FlyingActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_FlyingActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_FlyingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RFly.started += instance.OnRFly;
                @RFly.performed += instance.OnRFly;
                @RFly.canceled += instance.OnRFly;
                @Grip.started += instance.OnGrip;
                @Grip.performed += instance.OnGrip;
                @Grip.canceled += instance.OnGrip;
                @LFly.started += instance.OnLFly;
                @LFly.performed += instance.OnLFly;
                @LFly.canceled += instance.OnLFly;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public FlyingActions @Flying => new FlyingActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private IDebugActions m_DebugActionsCallbackInterface;
    private readonly InputAction m_Debug_ToggleCars;
    private readonly InputAction m_Debug_ToggleText;
    private readonly InputAction m_Debug_IncreaseVelocity;
    private readonly InputAction m_Debug_DecreaseVelocity;
    public struct DebugActions
    {
        private @InputManager m_Wrapper;
        public DebugActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleCars => m_Wrapper.m_Debug_ToggleCars;
        public InputAction @ToggleText => m_Wrapper.m_Debug_ToggleText;
        public InputAction @IncreaseVelocity => m_Wrapper.m_Debug_IncreaseVelocity;
        public InputAction @DecreaseVelocity => m_Wrapper.m_Debug_DecreaseVelocity;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void SetCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterface != null)
            {
                @ToggleCars.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleCars;
                @ToggleCars.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleCars;
                @ToggleCars.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleCars;
                @ToggleText.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleText;
                @ToggleText.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleText;
                @ToggleText.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnToggleText;
                @IncreaseVelocity.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnIncreaseVelocity;
                @IncreaseVelocity.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnIncreaseVelocity;
                @IncreaseVelocity.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnIncreaseVelocity;
                @DecreaseVelocity.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDecreaseVelocity;
                @DecreaseVelocity.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDecreaseVelocity;
                @DecreaseVelocity.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDecreaseVelocity;
            }
            m_Wrapper.m_DebugActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ToggleCars.started += instance.OnToggleCars;
                @ToggleCars.performed += instance.OnToggleCars;
                @ToggleCars.canceled += instance.OnToggleCars;
                @ToggleText.started += instance.OnToggleText;
                @ToggleText.performed += instance.OnToggleText;
                @ToggleText.canceled += instance.OnToggleText;
                @IncreaseVelocity.started += instance.OnIncreaseVelocity;
                @IncreaseVelocity.performed += instance.OnIncreaseVelocity;
                @IncreaseVelocity.canceled += instance.OnIncreaseVelocity;
                @DecreaseVelocity.started += instance.OnDecreaseVelocity;
                @DecreaseVelocity.performed += instance.OnDecreaseVelocity;
                @DecreaseVelocity.canceled += instance.OnDecreaseVelocity;
            }
        }
    }
    public DebugActions @Debug => new DebugActions(this);
    public interface IFlyingActions
    {
        void OnRFly(InputAction.CallbackContext context);
        void OnGrip(InputAction.CallbackContext context);
        void OnLFly(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
    public interface IDebugActions
    {
        void OnToggleCars(InputAction.CallbackContext context);
        void OnToggleText(InputAction.CallbackContext context);
        void OnIncreaseVelocity(InputAction.CallbackContext context);
        void OnDecreaseVelocity(InputAction.CallbackContext context);
    }
}
